image: 533135976680.dkr.ecr.us-west-2.amazonaws.com/gitlab-runner-node:14.15.4-alpine3.12

cache:
  paths:
    - /node-modules

stages:
  - test
  - build

lint:
  stage: test
  script:
    - npm ci --progress=false
    - npm run lint

test:
  stage: test
  script:
    - npm ci --progress=false
    - npm run test

build:
  stage: build
  script:
    - npm ci --progress=false
    - npm run build
